// pages/index.vue
<template>
  <div class="bg-dark">
    <div class="container-fluid bg-dark" style="height: 100vh">
      <div class="container py-5 bg-dark">
        <div class="text-center">
          <h1 class="main-title mb-3">
            <span class="marker marker-neon-yellow px-md-4 py-md-3 py-2 px-2">
              #ManOfTheMatch
            </span>
          </h1>
          <p class="text-monospace">
            <span class="marker marker-neon-yellow marker-tag">
              <i> Developed by Team Blklight</i>
            </span>
          </p>

          <h2 class="mt-3 mb-4" style="font-weight: 900">
            <span class="marker marker-neon-yellow marker-tag px-3">
              <strong> <em>2021/1</em></strong>
            </span>
          </h2>
        </div>
        <div class="container">
          <div :class="show ? 'fade-out-bottom' : ''">
            <button
              class="
                btn btn-flat btn-block btn-neon-yellow
                mx-auto
                d-block
                w-50
              "
              @click="play"
            >
              Ver o(s) vencedor(es)!
            </button>
          </div>

          <div v-if="show" :class="show ? 'fade-in-bottom' : ''">
            <div class="mb-4">
              <h2 class="marker marker-neon-yellow marker-tag mb-3">
                <span class="">
                  <strong><em>Vencedor(es)</em></strong>
                </span>
              </h2>
              <img
                v-lazy="winner"
                class="img-fluid mx-auto d-block"
                :alt="winnerName"
                :title="winnerName"
              />
              <p class="text-neon-yellow text-center my-3">
                <em>
                  <a
                    :href="winnerHD"
                    class="marker marker-link marker-neon-yellow mx-1"
                    target="_blank"
                  >
                    Clique aqui
                  </a>
                  para baixar a versão em HD.
                </em>
              </p>
            </div>
            <div class="mb-4">
              <h3 class="mb-3">
                <span class="marker marker-neon-yellow marker-tag">
                  <strong><em> 2ª colocação </em></strong>
                </span>
              </h3>
              <template v-for="(second, i) in seconds">
                <p :key="i" class="text-neon-yellow text-size">
                  <em>"{{ second.quote }}" - {{ second.name }}</em>
                </p>
              </template>
            </div>
            <div class="mb-4">
              <h3 class="mb-3">
                <span class="marker marker-neon-yellow marker-tag">
                  <strong><em> 3ª colocação </em></strong>
                </span>
              </h3>
              <template v-for="(third, i) in thirds">
                <p :key="i" class="text-neon-yellow text-size">
                  <em>"{{ third.quote }}" - {{ third.name }}</em>
                </p>
              </template>
            </div>
            <div class="mb-4">
              <h2 class="mb-3">
                <span class="marker marker-neon-yellow marker-tag">
                  <strong><em> Bônus </em></strong>
                </span>
              </h2>
              <h4 class="marker marker-neon-yellow marker-tag mb-3">
                <span class="">
                  <strong><em> Daft Vitola - Wallpaper </em></strong>
                </span>
              </h4>
              <img
                v-lazy="daft"
                class="img-fluid mx-auto d-block"
                alt="Daft Vitola"
                title="Daft Vitola"
              />
              <p class="text-neon-yellow text-center my-3">
                <em>
                  <a
                    :href="daftHD"
                    class="marker marker-link marker-neon-yellow mx-1"
                    target="_blank"
                  >
                    Clique aqui
                  </a>
                  para baixar a versão em HD.
                </em>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { Howl } from 'howler'

import urna from '~/assets/audio/urna.mp3'

import dataSecond from '~/assets/data/seconds.json'
import dataThird from '~/assets/data/thirds.json'
export default {
  data() {
    return {
      sound: '',
      show: false,
      winnerName: 'Ultimate',
      winner: 'https://i.imgur.com/qb7PZXm.jpg',
      winnerHD: 'https://i.imgur.com/cSRyYIx.jpg',
      daft: 'https://i.imgur.com/3ndugq6.jpg',
      daftHD: 'https://i.imgur.com/bZQauq4.jpg',
      seconds: dataSecond,
      thirds: dataThird,
    }
  },
  mounted() {
    this.sound = new Howl({
      src: [urna],

      onloaderror(id, err) {
        console.warn('failed to load sound file:', { id, err })
      },
    })
  },
  methods: {
    play() {
      this.sound.play()
      setTimeout(() => (this.show = true), 300)
      clearTimeout()
    },

    showWinner() {},
  },
}
</script>

<style lang="scss">
body {
  background-color: #121212;
}
.main-title {
  font-weight: 900;
  font-style: italic;
  font-size: 88px;
  font-family: 'Exo', sans-serif;
}
@media screen and (max-width: 992px) {
  .main-title {
    font-size: 64px;
  }
}
@media screen and (max-width: 768px) {
  .main-title {
    font-size: 56px;
  }
}
@media screen and (max-width: 576px) {
  .main-title {
    font-size: 2.5rem;
  }
}

.freebirdFormviewerViewCenteredContent {
  width: 100% !important;
  max-width: 100% !important;
  margin: 0 auto;
}

.text-size {
  font-size: 20px;
}

.fade-in-bottom {
  -webkit-animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s
    both;
  animation: fade-in-bottom 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) 2s both;
}

.fade-out-bottom {
  -webkit-animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    0.5s both;
  animation: fade-out-bottom 0.6s cubic-bezier(0.25, 0.46, 0.45, 0.94) 0.5s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-7-3 17:54:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}

/**
 * ----------------------------------------
 * animation fade-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
@keyframes fade-out-bottom {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(50px);
    transform: translateY(50px);
    opacity: 0;
  }
}
</style>

// pages/index.tsx
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { Howl, Howler } from "howler";
import { cn } from "@/lib/utils";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

import { getAllChampions } from "@/lib/services";
import ChampionCard from "@/components/ChampionCard";
import { Button } from "@/components/ui/button";
import Footer from "@/components/Footer";
import Head from "next/head";
import { useState } from "react";

export const metadata: Metadata = {
  title: "#ManOfTheMatch",
  description: "",
};

export async function getStaticProps() {
  const champions = await getAllChampions();
  return { props: { champions } };
}

const Home = ({ champions }: any) => {
  const [show, setShow] = useState(false);

  const sound = new Howl({
    src: ["/urna.mp3"],
    onloaderror(id, err) {
      // eslint-disable-next-line no-console
      console.warn("failed to load sound file:", { id, err });
    },
  });

  const winners = [
    {
      photo: "https://i.imgur.com/nQ1MWHe.jpg",
      photoHD: "https://i.imgur.com/ENK4JCt.jpg",
    },
    {
      photo: "https://i.imgur.com/hW3jzGf.jpg",
      photoHD: "https://i.imgur.com/HFS85z7.jpg",
    },
  ];

  const seconds = [
    {
      quote: "Sentimento muito bom, é comer casada.",
      name: "Ultimate WNDL",
    },
  ];

  const thirds = [
    {
      quote: "O cara que respira tecnologia é o rodrigo que usa nebulizador",
      name: "Ultimate",
    },
  ];

  const play = () => {
    sound.play();
  };
  return (
    <>
      <Head>
        <title>#ManOfTheMatch</title>
      </Head>
      <div className="container mx-auto py-4">
        <div className="mb-5">
          <h1 className="lg:text-8xl text-6xl font-bold header-name mb-4">
            <span className="background-texture marker-line !px-4 !py-3 bg-orange-300 text-dark-500"></span>
          </h1>
          <p className="text-xl font-medium">
            <span className="marker-line !px-3 !py-1 bg-orange-300 text-dark-500">
              Developed by Team Blklight
            </span>
          </p>
        </div>
        <Tabs defaultValue="season" className="w-full">
          <TabsList>
            <TabsTrigger value="season">Votes - 2023/2 </TabsTrigger>
            <TabsTrigger value="champions" onClick={() => play()}>
              All Time Champions
            </TabsTrigger>
            <TabsTrigger value="bonus" onClick={() => play()}>
              Bonus
            </TabsTrigger>
          </TabsList>
          <TabsContent value="season" className="glass">
            <div className="card card-plain card-body">
              <Button
                className="bg-orange-300 text-dark-500 hover:bg-orange-600 hover:text-light-500 text-xl"
                size={"lg"}
                onClick={() => {
                  play();
                  setShow(!show);
                }}
              >
                Champions of the season
              </Button>
              {show && (
                <section
                  className={`my-5 transition-all ${
                    show ? "fade-in-bottom" : "fade-out-bottom"
                  }`}
                >
                  <div className="mb-4">
                    <h3 className="text-3xl font-bold bg-orange-300 text-dark-500 tracking-wide mb-2">
                      <span className="marker-line"> Winner(s) </span>
                    </h3>
                    {winners.map((winner, index) => (
                      <div key={index}>
                        <img
                          src={winner.photo}
                          className="w-full h-auto mx-auto my-4"
                          alt={`avatar`}
                        />
                        <div className="flex justify-center my-2">
                          <Button
                            className="bg-orange-300 text-dark-500 hover:bg-orange-600 hover:text-light-500 rounded-sm"
                            size={"sm"}
                            asChild
                          >
                            <Link href={winner.photoHD} target="_blank">
                              Download HD Version
                            </Link>
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>

                  <div className="mb-4">
                    <h4 className="text-2xl font-bold bg-orange-300 text-dark-500 mb-2">
                      <span className="marker-line"> 2ª place</span>
                    </h4>
                    <div className="px-2">
                      {seconds.map((second, key) => (
                        <p
                          key={key}
                          className="text-xl text-dark-500 font-medium mb-2"
                        >
                          {second.quote} - {second.name}
                        </p>
                      ))}
                    </div>
                  </div>
                  <div className="mb-4">
                    <h4 className="text-2xl font-bold bg-orange-300 text-dark-500 mb-2">
                      <span className="marker-line"> 3ª place</span>
                    </h4>
                    <div className="px-2">
                      {thirds.map((third, key) => (
                        <p
                          key={key}
                          className="text-xl text-dark-500 font-medium mb-2"
                        >
                          {third.quote} - {third.name}
                        </p>
                      ))}
                    </div>
                  </div>
                </section>
              )}

              {/* <iframe
                src=""
                width="640"
                height="2550"
                className="iframe-style-force mx-auto block"
              >
                Carregando…
              </iframe> */}
            </div>
          </TabsContent>
          <TabsContent value="champions" className="!transparent py-4">
            {champions.map((champion: any) => (
              <ChampionCard champion={champion} key={champion.name} />
            ))}
          </TabsContent>

          <TabsContent value="bonus" className="glass">
            <div className="card card-plain card-body">
              <h3 className="text-3xl font-bold bg-orange-300 text-dark-500 mb-4">
                <span className="marker-line !py-1">
                  Daft Vitola - Wallpaper
                </span>
              </h3>
              <img
                src="https://i.imgur.com/3ndugq6.jpg"
                className="w-full h-auto mx-auto mb-4"
                alt=""
              />
              <Button
                className="bg-orange-300 text-dark-500 hover:bg-orange-600 hover:text-light-500"
                asChild
              >
                <Link
                  href={"https://i.imgur.com/bZQauq4.jpg"}
                  className="bg-orange-300 text-dark-500 hover:bg-orange-600 hover:text-light-500 flex"
                  target="_blank"
                >
                  Clique aqui para fazer o download da versão em HD.
                </Link>
              </Button>
            </div>
          </TabsContent>
        </Tabs>
      </div>
      <Footer />
    </>
  );
};

export default Home;
